import React from 'react'
import Footer from './Footer'
import Head from 'next/head'
import Header from './Header'
import Content from './Content'

const Layout = () => {
  return (
    <>
    <Head>
        <title>Exam Portal</title>
        <meta name="description" content="Generated by create next app" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossOrigin="anonymous"></link>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Header/>
    <Content/>
    {/* <Footer/> */}
    </>
  )
}

export default Layout